"""add_payable_receivable_to_transaction_type

Revision ID: a0ab2b840a85
Revises: 36c7032ff4b8
Create Date: 2026-07-07 07:23:46.117600

"""
from alembic import op
import sqlalchemy as sa


revision = 'a0ab2b840a85'
down_revision = '36c7032ff4b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'trans_type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('debit', 'credit', 'payable', 'receivable', name='transactiontype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: the original autogenerated downgrade narrowed trans_type back to
    # VARCHAR(6), which truncates 'receivable' (10 chars) / 'payable' (7) and errors.
    # Widened to VARCHAR(10) so this migration's downgrade is correct in isolation.
    op.alter_column('transactions', 'trans_type',
               existing_type=sa.Enum('debit', 'credit', 'payable', 'receivable', name='transactiontype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
